# Generated by Django 3.2.9 on 2022-01-04 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('use', 'use'), ('proposal', 'proposal'), ('login', 'login'), ('report', 'report'), ('etc', 'etc')], max_length=80, null=True),
        ),
    ]
