# Generated by Django 3.2.6 on 2021-09-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('use', 'use'), ('report', 'report'), ('login', 'login'), ('etc', 'etc'), ('proposal', 'proposal')], max_length=80, null=True),
        ),
    ]
