# Generated by Django 3.2.6 on 2021-08-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_write_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
