# Generated by Django 3.2.9 on 2022-01-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('etc', 'etc'), ('proposal', 'proposal'), ('login', 'login'), ('report', 'report'), ('use', 'use')], max_length=80, null=True),
        ),
    ]
