# Generated by Django 3.2.9 on 2021-12-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211205_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('proposal', 'proposal'), ('use', 'use'), ('report', 'report'), ('etc', 'etc'), ('login', 'login')], max_length=80, null=True),
        ),
    ]
