# Generated by Django 3.2.9 on 2022-01-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220104_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('proposal', 'proposal'), ('etc', 'etc'), ('login', 'login'), ('use', 'use'), ('report', 'report')], max_length=80, null=True),
        ),
    ]
