# Generated by Django 3.2.6 on 2021-09-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('etc', 'etc'), ('report', 'report'), ('use', 'use'), ('login', 'login'), ('proposal', 'proposal')], max_length=80, null=True),
        ),
    ]
