# Generated by Django 3.2.6 on 2021-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('login', 'login'), ('use', 'use'), ('proposal', 'proposal'), ('etc', 'etc'), ('report', 'report')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='useremail',
            field=models.EmailField(max_length=128, null=True),
        ),
    ]
